# Generated by Django 2.0.3 on 2018-04-12 21:01

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('available_over_sea', models.BooleanField(default=False)),
                ('willing_play_in_another_band', models.BooleanField(default=False)),
                ('perform_radius', models.IntegerField()),
                ('minimum_hour_rate', models.IntegerField()),
                ('artists', models.ManyToManyField(to='soundbuddy.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EventKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MusicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='events',
            field=models.ManyToManyField(to='soundbuddy.Event'),
        ),
        migrations.AddField(
            model_name='band',
            name='music_types',
            field=models.ManyToManyField(to='soundbuddy.MusicType'),
        ),
        migrations.AddField(
            model_name='band',
            name='photos',
            field=models.ManyToManyField(to='soundbuddy.Photo'),
        ),
        migrations.AddField(
            model_name='band',
            name='preferred_events',
            field=models.ManyToManyField(to='soundbuddy.EventKind'),
        ),
        migrations.AddField(
            model_name='band',
            name='tracks',
            field=models.ManyToManyField(to='soundbuddy.Track'),
        ),
        migrations.AddField(
            model_name='band',
            name='videos',
            field=models.ManyToManyField(to='soundbuddy.Video'),
        ),
    ]
