# Generated by Django 2.0.3 on 2018-04-22 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundbuddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='band',
            old_name='willing_play_in_another_band',
            new_name='willing_play_in_another_configuration',
        ),
        migrations.AddField(
            model_name='artist',
            name='bands',
            field=models.ManyToManyField(null=True, to='soundbuddy.Band'),
        ),
        migrations.AddField(
            model_name='artist',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='adress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundbuddy.EventKind'),
        ),
        migrations.AddField(
            model_name='event',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='special_requirements',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eventkind',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='musictype',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='url',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='artists',
            field=models.ManyToManyField(null=True, to='soundbuddy.Artist'),
        ),
        migrations.AlterField(
            model_name='band',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='events',
            field=models.ManyToManyField(null=True, to='soundbuddy.Event'),
        ),
        migrations.AlterField(
            model_name='band',
            name='minimum_hour_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='music_types',
            field=models.ManyToManyField(null=True, to='soundbuddy.MusicType'),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='perform_radius',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='photos',
            field=models.ManyToManyField(null=True, to='soundbuddy.Photo'),
        ),
        migrations.AlterField(
            model_name='band',
            name='preferred_events',
            field=models.ManyToManyField(null=True, to='soundbuddy.EventKind'),
        ),
        migrations.AlterField(
            model_name='band',
            name='tracks',
            field=models.ManyToManyField(null=True, to='soundbuddy.Track'),
        ),
        migrations.AlterField(
            model_name='band',
            name='videos',
            field=models.ManyToManyField(null=True, to='soundbuddy.Video'),
        ),
    ]
