# Generated by Django 2.0.3 on 2018-04-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundbuddy', '0004_auto_20180423_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='band',
            name='tracks',
        ),
        migrations.RemoveField(
            model_name='band',
            name='videos',
        ),
        migrations.AddField(
            model_name='photo',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundbuddy.Band'),
        ),
        migrations.AddField(
            model_name='track',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundbuddy.Band'),
        ),
        migrations.AddField(
            model_name='video',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundbuddy.Band'),
        ),
    ]
