# Generated by Django 2.0.3 on 2018-03-22 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='name',
            field=models.CharField(default='Band', max_length=30),
        ),
        migrations.AddField(
            model_name='musician',
            name='band',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Band'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musician',
            name='name',
            field=models.CharField(default='Musician', max_length=30),
        ),
    ]
